[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bitflags = "2.13.2"
circular-buffer = { version = "2.0.1", default-features = false }
heapless = "0.9.3"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
log = "0.4.34"
spin = "0.12.3"

[workspace.lints.clippy]
cast_ptr_alignment = "warn"  # TODO: address occurrences and then deny
identity_op = "allow"  # Used to allow stuff like 1 << 0 and 1 * 1024 * 1024
if_same_then_else = "allow"  # Useful for adding comments about different branches
many_single_char_names = "allow"  # Useful in the syscall function
module_inception = "allow"  # Used for context::context
# Not implementing default is sometimes useful in the case something has significant cost
# to allocate. If you implement default, it can be allocated without evidence using the
# ..Default::default() syntax. Not fun in kernel space
new_without_default = "allow"
not_unsafe_ptr_arg_deref = "deny"
or_fun_call = "allow"  # Used to make it nicer to return errors, for example, .ok_or(Error::new(ESRCH))
precedence = "deny"
ptr_cast_constness = "deny"
too_many_arguments = "allow"  # This is needed in some cases, like for syscall
# Avoid panicking in the kernel without information about the panic. Use expect
# TODO: address occurrences and then deny
unwrap_used = "warn"

[workspace.lints.rust]
static_mut_refs = "warn"  # FIXME deny once all occurrences are fixed
# This is usually a serious issue - a missing import of a define where it is interpreted
# as a catch-all variable in a match, for example
unreachable_patterns = "deny"
unused_must_use = "deny"  # Ensure that all must_use results are used
